### ISSUE TITLE
General request

### ISSUE THREAD

**Issue by sassy-ankit** [jmcgrory/MEAN-Stack-Blogging-CMS#1]
Do u need any collaborator to help you complete this project. 
I am learning MEAN4 and consider myself to be at 'intermediate' level. 
This collaboration may help you get out of bottle neck and also give me practice and most importantly experience to work on a team like situation..? 
Awaiting reply. 
Thanx

**Comment by jmcgrory** [comment]
Apologies for the late reply, I'm still getting this live as a personal project at which point I may whitelabel and put out as a collaborative project. Cheers.
